#!/usr/bin/env python3
import argparse
import hashlib
import json
import os
from pathlib import Path
import tempfile


SKILL_ROOT = Path(__file__).resolve().parents[1]
DEFAULTS = SKILL_ROOT / 'config/models.default.json'
FIELDS = ('transport', 'model', 'reasoning_effort')
EFFORTS = {'none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'}
TRANSPORTS = {'native', 'codex-cli', 'claude-cli'}
FALLBACK_PROFILE = 'default'
DEFAULT_EFFORT_NAMES = {'default', 'null'}
CLAUDE_EFFORTS = {'low', 'medium', 'high', 'xhigh', 'max'}
CLAUDE_ALIASES = {'sonnet', 'opus', 'haiku', 'fable', 'inherit', 'default', 'best', 'opusplan'}
CLAUDE_PROFILE = 'claude-code'
CLAUDE_AGENT = 'fusion-sidekick'
AGENT_MARKER = '<!-- Generated by fusion-harness model_config.py. Changes are overwritten; edit models.json instead. -->'


def effort_argument(value):
    return None if value in DEFAULT_EFFORT_NAMES else value


def user_path():
    explicit = os.environ.get('FUSION_MODELS_FILE')
    if explicit:
        return Path(explicit).expanduser()
    config_home = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config').expanduser()
    return config_home / 'fusion-harness/models.json'


def claude_agent_path():
    config = Path(os.environ.get('CLAUDE_CONFIG_DIR') or Path.home() / '.claude').expanduser()
    return config / 'agents' / f'{CLAUDE_AGENT}.md'


def validate(data):
    if not isinstance(data, dict) or set(data) != {'version', 'sidekicks'} or type(data['version']) is not int or data['version'] != 2:
        raise ValueError('Expected version 2 and exactly the version and sidekicks keys.')
    profiles = data['sidekicks']
    if not isinstance(profiles, dict) or FALLBACK_PROFILE not in profiles:
        raise ValueError(f'sidekicks must be an object with a "{FALLBACK_PROFILE}" profile.')
    for name, settings in profiles.items():
        if not name or name != name.strip() or any(c.isspace() for c in name):
            raise ValueError('Profile names must be nonempty and contain no whitespace.')
        if not isinstance(settings, dict) or set(settings) != set(FIELDS):
            raise ValueError(f'sidekicks.{name} must contain exactly transport, model, and reasoning_effort.')
        if settings['transport'] not in TRANSPORTS:
            raise ValueError(f'sidekicks.{name}.transport must be one of {sorted(TRANSPORTS)}.')
        model = settings['model']
        if not isinstance(model, str) or not model or any(c.isspace() for c in model):
            raise ValueError(f'sidekicks.{name}.model must be a nonempty model identifier without whitespace.')
        effort = settings['reasoning_effort']
        if effort is not None and effort not in EFFORTS:
            raise ValueError(f'sidekicks.{name}.reasoning_effort must be null or one of {sorted(EFFORTS)}.')
    if profiles[FALLBACK_PROFILE]['transport'] == 'native':
        raise ValueError(f'The "{FALLBACK_PROFILE}" profile must use a CLI transport so it works in any harness.')
    return data


def read_overrides(path):
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as exc:
        raise ValueError(f'{path} is not valid JSON: {exc}') from exc
    if not isinstance(data, dict) or set(data) != {'version', 'sidekicks'} or data['version'] != 2 or not isinstance(data['sidekicks'], dict):
        raise ValueError(f'{path} must contain version 2 and a sidekicks object.')
    for name, settings in data['sidekicks'].items():
        if not isinstance(settings, dict) or not set(settings) <= set(FIELDS):
            raise ValueError(f'{path}: sidekicks.{name} may only set {list(FIELDS)}.')
    return data['sidekicks']


def merge(defaults, overrides):
    profiles = {name: {**settings, **overrides.get(name, {})} for name, settings in defaults['sidekicks'].items()}
    for name, settings in overrides.items():
        if name not in profiles:
            profiles[name] = {**profiles.get(FALLBACK_PROFILE, {}), **settings}
    return validate({'version': 2, 'sidekicks': profiles})


def read():
    path = user_path()
    overrides = read_overrides(path)
    data = merge(json.loads(DEFAULTS.read_text()), overrides)
    revision = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:16]
    return {'path': str(path), 'overrides': overrides, 'revision': revision, 'models': data}


def uses_claude(name, settings):
    return settings['transport'] == 'claude-cli' or (name == CLAUDE_PROFILE and settings['transport'] == 'native')


def check_claude(name, settings):
    if not uses_claude(name, settings):
        return
    fix = f'Run model_config.py set --profile {name} --model <full-id> --effort <effort>.'
    if settings['model'] in CLAUDE_ALIASES:
        raise ValueError(f'sidekicks.{name}.model must be a full Claude model ID such as claude-sonnet-5-5, not an alias. {fix}')
    if settings['reasoning_effort'] is not None and settings['reasoning_effort'] not in CLAUDE_EFFORTS:
        raise ValueError(f'sidekicks.{name}.reasoning_effort must be null or one of {sorted(CLAUDE_EFFORTS)} for Claude. {fix}')


def claude_agent_text(settings):
    lines = ['---', f'name: {CLAUDE_AGENT}',
             'description: Persistent sidekick for a Fusion lead. Use only when the fusion skill starts its sidekick.',
             f'model: {settings["model"]}']
    if settings['reasoning_effort']:
        lines.append(f'effort: {settings["reasoning_effort"]}')
    contract = SKILL_ROOT / 'references/sidekick.md'
    lines += ['---', '', AGENT_MARKER, '', f'You are the Fusion sidekick. Before your first brief, read {contract} and follow it for this whole session.', '']
    return '\n'.join(lines)


def prepare_claude_agent(settings):
    path = claude_agent_path()
    status = {'agent_type': CLAUDE_AGENT, 'agent_file': str(path), 'reload_required': False, 'restart_required': False}
    expected = claude_agent_text(settings)
    try:
        existing = path.read_text()
    except FileNotFoundError:
        existing = None
    if existing == expected:
        return status
    if existing is not None and AGENT_MARKER not in existing:
        return {**status, 'error': f'{path} exists and was not generated by fusion-harness. Move it away and resolve again.'}
    created_folder = not path.parent.is_dir()
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile('w', dir=path.parent, delete=False, suffix='.tmp') as output:
        output.write(expected)
    os.replace(output.name, path)
    return {**status, 'reload_required': True, 'restart_required': created_folder}


def settings_of(item):
    return tuple(item[field] for field in FIELDS)


def resolve(harness, active=None):
    loaded = read()
    profiles = loaded['models']['sidekicks']
    profile = harness if harness in profiles else FALLBACK_PROFILE
    selected = dict(profiles[profile])
    check_claude(profile, selected)
    action = 'spawn' if active is None else 'reuse' if settings_of(active) == settings_of(selected) else 'replace_after_handoff'
    result = {'harness': harness, 'profile': profile, 'action': action, **selected, 'revision': loaded['revision']}
    if profile == CLAUDE_PROFILE and selected['transport'] == 'native':
        result.update(prepare_claude_agent(selected))
    return result


def write_overrides(path, overrides):
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile('w', dir=path.parent, delete=False, suffix='.tmp') as output:
        output.write(json.dumps({'version': 2, 'sidekicks': overrides}, indent=2) + '\n')
    os.replace(output.name, path)


def update(profile, transport=None, model=None, effort=None):
    path = user_path()
    overrides = read_overrides(path)
    change = dict(overrides.get(profile, {}))
    if transport:
        change['transport'] = transport
    if model:
        change['model'] = model
    if effort:
        change['reasoning_effort'] = effort_argument(effort)
    candidate = {**overrides, profile: change}
    merged = merge(json.loads(DEFAULTS.read_text()), candidate)
    check_claude(profile, merged['sidekicks'][profile])
    write_overrides(path, candidate)
    return read()


def reset(profile):
    path = user_path()
    overrides = read_overrides(path)
    if profile in overrides:
        remaining = {name: settings for name, settings in overrides.items() if name != profile}
        merge(json.loads(DEFAULTS.read_text()), remaining)
        write_overrides(path, remaining)
    return read()


def main():
    parser = argparse.ArgumentParser(description='Resolve Fusion sidekick settings from shipped defaults and the user overrides file.')
    commands = parser.add_subparsers(dest='command', required=True)
    commands.add_parser('show')
    sub = commands.add_parser('resolve')
    sub.add_argument('--harness', required=True)
    sub.add_argument('--active-transport', choices=sorted(TRANSPORTS))
    sub.add_argument('--active-model')
    sub.add_argument('--active-effort', help='Use "default" or "null" when the active sidekick has no explicit effort.')
    sub = commands.add_parser('set', help='Save a sidekick choice for future sessions.')
    sub.add_argument('--profile', required=True)
    sub.add_argument('--transport', choices=sorted(TRANSPORTS))
    sub.add_argument('--model')
    sub.add_argument('--effort', choices=sorted(EFFORTS | DEFAULT_EFFORT_NAMES))
    sub = commands.add_parser('reset', help='Return a profile to the shipped defaults.')
    sub.add_argument('--profile', required=True)
    args = parser.parse_args()
    try:
        if args.command == 'show':
            result = read()
        elif args.command == 'set':
            result = update(args.profile, args.transport, args.model, args.effort)
        elif args.command == 'reset':
            result = reset(args.profile)
        else:
            given = [args.active_transport, args.active_model, args.active_effort]
            if any(given) and not all(given):
                raise ValueError('Pass all of --active-transport, --active-model, and --active-effort, or none.')
            active = None
            if all(given):
                active = {'transport': args.active_transport, 'model': args.active_model, 'reasoning_effort': effort_argument(args.active_effort)}
            result = resolve(args.harness, active)
        print(json.dumps(result, indent=2))
    except (OSError, ValueError) as exc:
        parser.exit(1, f'Fusion model configuration: {exc}\n')


if __name__ == '__main__':
    main()
