#!/usr/bin/env python3
import argparse
import hashlib
import json
import os
from pathlib import Path
import tempfile


SKILL_ROOT = Path(__file__).resolve().parents[1]
DEFAULTS = SKILL_ROOT / 'config/models.default.json'
EFFORTS = {'none', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'}
CLAUDE_EFFORTS = {'low', 'medium', 'high', 'xhigh', 'max'}
CLAUDE_ALIASES = {'sonnet', 'opus', 'haiku', 'fable', 'inherit', 'default', 'best', 'opusplan'}
CLAUDE_PROFILE = 'claude-code'
CLAUDE_AGENT = 'fusion-sidekick'
AGENT_MARKER = '<!-- Generated by fusion-harness model_config.py. Changes are overwritten; edit models.json instead. -->'
TRANSPORTS = {'native', 'codex-cli', 'claude-cli'}
FALLBACK_PROFILE = 'default'
DEFAULT_EFFORT_NAMES = {'default', 'null'}


def effort_argument(value):
    return None if value in DEFAULT_EFFORT_NAMES else value


def live_path():
    explicit = os.environ.get('FUSION_MODELS_FILE')
    if explicit:
        return Path(explicit).expanduser()
    config_home = Path(os.environ.get('XDG_CONFIG_HOME') or Path.home() / '.config').expanduser()
    return config_home / 'fusion-harness/models.json'


def claude_agent_path():
    config = Path(os.environ.get('CLAUDE_CONFIG_DIR') or Path.home() / '.claude').expanduser()
    return config / 'agents' / f'{CLAUDE_AGENT}.md'


def uses_claude(name, settings):
    return settings['transport'] == 'claude-cli' or (name == CLAUDE_PROFILE and settings['transport'] == 'native')


def check_claude(name, settings):
    if not uses_claude(name, settings):
        return
    fix = f'Run model_config.py set --profile {name} --model <full-id> --effort <effort>.'
    if settings['model'] in CLAUDE_ALIASES:
        raise ValueError(f'sidekicks.{name}.model must be a full Claude model ID such as claude-sonnet-5-5, not an alias. {fix}')
    if settings['reasoning_effort'] is not None and settings['reasoning_effort'] not in CLAUDE_EFFORTS:
        raise ValueError(f'sidekicks.{name}.reasoning_effort must be null or one of {sorted(CLAUDE_EFFORTS)} for Claude. {fix}')


def legacy_path():
    codex_home = Path(os.environ.get('CODEX_HOME') or Path.home() / '.codex').expanduser()
    return codex_home / 'plugins/fusion/models.json'


def validate(data):
    if not isinstance(data, dict) or set(data) != {'version', 'sidekicks'} or type(data['version']) is not int or data['version'] != 2:
        raise ValueError('Expected version 2 and exactly the version and sidekicks keys.')
    profiles = data['sidekicks']
    if not isinstance(profiles, dict) or FALLBACK_PROFILE not in profiles:
        raise ValueError(f'sidekicks must be an object with a "{FALLBACK_PROFILE}" profile.')
    for name, settings in profiles.items():
        if not name or name != name.strip() or any(c.isspace() for c in name):
            raise ValueError('Profile names must be nonempty and contain no whitespace.')
        if not isinstance(settings, dict) or set(settings) != {'transport', 'model', 'reasoning_effort'}:
            raise ValueError(f'sidekicks.{name} must contain exactly transport, model, and reasoning_effort.')
        if settings['transport'] not in TRANSPORTS:
            raise ValueError(f'sidekicks.{name}.transport must be one of {sorted(TRANSPORTS)}.')
        model = settings['model']
        if not isinstance(model, str) or not model or any(c.isspace() for c in model):
            raise ValueError(f'sidekicks.{name}.model must be a nonempty model identifier without whitespace.')
        effort = settings['reasoning_effort']
        if effort is not None and effort not in EFFORTS:
            raise ValueError(f'sidekicks.{name}.reasoning_effort must be null or one of {sorted(EFFORTS)}.')
    if profiles[FALLBACK_PROFILE]['transport'] == 'native':
        raise ValueError(f'The "{FALLBACK_PROFILE}" profile must use a CLI transport so it works in any harness.')
    return data


def read():
    path = live_path()
    try:
        data = validate(json.loads(path.read_text()))
    except FileNotFoundError as exc:
        raise ValueError(f'No model file at {path}. Run model_config.py init.') from exc
    revision = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:16]
    return {'path': str(path.resolve()), 'revision': revision, 'models': data}


def settings_of(item):
    return (item['transport'], item['model'], item['reasoning_effort'])


def claude_agent_text(settings):
    lines = ['---', f'name: {CLAUDE_AGENT}',
             'description: Persistent sidekick for a Fusion lead. Use only when the fusion skill starts its sidekick.',
             f'model: {settings["model"]}']
    if settings['reasoning_effort']:
        lines.append(f'effort: {settings["reasoning_effort"]}')
    contract = SKILL_ROOT / 'references/sidekick.md'
    lines += ['---', '', AGENT_MARKER, '', f'You are the Fusion sidekick. Before your first brief, read {contract} and follow it for this whole session.', '']
    return '\n'.join(lines)


def claude_agent(loaded):
    settings = loaded['models']['sidekicks'].get(CLAUDE_PROFILE)
    if not settings or settings['transport'] != 'native':
        return None
    try:
        check_claude(CLAUDE_PROFILE, settings)
    except ValueError as exc:
        return {'agent_type': CLAUDE_AGENT, 'agent_file': str(claude_agent_path()), 'agent_file_current': False, 'error': str(exc)}
    path = claude_agent_path()
    status = {'agent_type': CLAUDE_AGENT, 'agent_file': str(path), 'agent_file_current': False}
    try:
        existing = path.read_text()
    except OSError:
        return status
    if AGENT_MARKER not in existing:
        return {**status, 'error': f'{path} exists and was not generated by fusion-harness. Move it away, then run model_config.py sync.'}
    return {**status, 'agent_file_current': existing == claude_agent_text(settings)}


def sync_claude_agent(loaded):
    status = claude_agent(loaded)
    if status and not status['agent_file_current'] and 'error' not in status:
        path = Path(status['agent_file'])
        path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile('w', dir=path.parent, delete=False, suffix='.tmp') as output:
            output.write(claude_agent_text(loaded['models']['sidekicks'][CLAUDE_PROFILE]))
        os.replace(output.name, path)
        status = {**status, 'agent_file_current': True, 'agent_file_written': True}
    return status


def resolve_loaded(loaded, harness, active=None):
    profiles = loaded['models']['sidekicks']
    profile = harness if harness in profiles else FALLBACK_PROFILE
    selected = dict(profiles[profile])
    check_claude(profile, selected)
    native_claude = profile == CLAUDE_PROFILE and selected['transport'] == 'native'
    changed = 'restart_session' if native_claude and active and active['transport'] == 'native' else 'replace_after_handoff'
    action = 'spawn' if active is None else 'reuse' if settings_of(active) == settings_of(selected) else changed
    result = {'path': loaded['path'], 'revision': loaded['revision'], 'harness': harness, 'profile': profile, 'action': action, **selected}
    if native_claude:
        result.update(claude_agent(loaded))
    return result


def with_claude_agent(loaded):
    status = sync_claude_agent(loaded)
    return {**loaded, 'claude_agent': status} if status else loaded


def resolve(harness, active=None):
    return resolve_loaded(read(), harness, active)


def write_atomic(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile('w', dir=path.parent, delete=False, suffix='.tmp') as output:
        output.write(json.dumps(data, indent=2) + '\n')
    os.replace(output.name, path)


def imported_defaults():
    defaults = validate(json.loads(DEFAULTS.read_text()))
    source = legacy_path()
    if os.environ.get('FUSION_MODELS_FILE') or not source.is_file():
        return defaults, None
    try:
        legacy = json.loads(source.read_text())
        sidekick = legacy['sidekick']
        candidate = json.loads(json.dumps(defaults))
        candidate['sidekicks']['codex'] = {'transport': 'native', 'model': sidekick['model'], 'reasoning_effort': sidekick['reasoning_effort']}
        return validate(candidate), str(source)
    except (OSError, ValueError, KeyError, TypeError):
        return defaults, None


def initialize():
    path = live_path()
    if path.exists():
        return {**with_claude_agent(read()), 'created': False}
    data, source = imported_defaults()
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with path.open('x') as output:
            output.write(json.dumps(data, indent=2) + '\n')
    except FileExistsError:
        return {**with_claude_agent(read()), 'created': False}
    result = {**with_claude_agent(read()), 'created': True}
    if source:
        result['imported_from'] = source
    return result


def update(profile, transport=None, model=None, effort=None):
    loaded = read()
    data = json.loads(json.dumps(loaded['models']))
    current = data['sidekicks'].get(profile)
    if current is None and not (transport and model):
        raise ValueError(f'New profile {profile} needs --transport and --model.')
    candidate = dict(current or {'reasoning_effort': None})
    if transport:
        candidate['transport'] = transport
    if model:
        candidate['model'] = model
    if effort:
        candidate['reasoning_effort'] = effort_argument(effort)
    check_claude(profile, candidate)
    data['sidekicks'][profile] = candidate
    write_atomic(Path(loaded['path']), validate(data))
    return with_claude_agent(read())


def main():
    parser = argparse.ArgumentParser(description='Read and update live Fusion sidekick settings.')
    commands = parser.add_subparsers(dest='command', required=True)
    commands.add_parser('init')
    commands.add_parser('show')
    commands.add_parser('sync')
    sub = commands.add_parser('resolve')
    sub.add_argument('--harness', required=True)
    sub.add_argument('--active-transport', choices=sorted(TRANSPORTS))
    sub.add_argument('--active-model')
    sub.add_argument('--active-effort', help='Use "default" or "null" when the active sidekick has no explicit effort.')
    sub = commands.add_parser('set')
    sub.add_argument('--profile', required=True)
    sub.add_argument('--transport', choices=sorted(TRANSPORTS))
    sub.add_argument('--model')
    sub.add_argument('--effort', choices=sorted(EFFORTS | DEFAULT_EFFORT_NAMES))
    args = parser.parse_args()
    try:
        if args.command == 'init':
            result = initialize()
        elif args.command == 'show':
            result = read()
        elif args.command == 'sync':
            result = with_claude_agent(read())
        elif args.command == 'set':
            result = update(args.profile, args.transport, args.model, args.effort)
        else:
            given = [args.active_transport, args.active_model, args.active_effort]
            if any(given) and not all(given):
                raise ValueError('Pass all of --active-transport, --active-model, and --active-effort, or none.')
            active = None
            if all(given):
                active = {'transport': args.active_transport, 'model': args.active_model, 'reasoning_effort': effort_argument(args.active_effort)}
            result = resolve(args.harness, active)
        print(json.dumps(result, indent=2))
    except (OSError, ValueError) as exc:
        parser.exit(1, f'Fusion model configuration: {exc}\n')


if __name__ == '__main__':
    main()
